"use client";

import { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import { GrainOverlay } from "@/components/layout/GrainOverlay";
import { BlobBackground } from "@/components/layout/BlobBackground";
import { Section } from "@/components/layout/Section";
import { Card } from "@/components/ui/Card";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { SkillSuggestions } from "@/components/features/SkillSuggestions";
import { 
  Shield, 
  ShieldAlert, 
  TrendingUp, 
  AlertTriangle, 
  CheckCircle, 
  ArrowLeft,
  Calendar,
  FileText,
  BarChart3,
  Download,
  Share2
} from "lucide-react";
import { motion } from "framer-motion";
import type { HistoryEntry, PredictionResult } from "@/types/prediction";
import Link from "next/link";

export default function AnalysisDetail() {
  const params = useParams();
  const router = useRouter();
  const [entry, setEntry] = useState<HistoryEntry | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const loadEntry = () => {
      const saved = localStorage.getItem("job-analysis-history");
      if (saved) {
        try {
          const history: HistoryEntry[] = JSON.parse(saved);
          console.log("Loaded history:", history.length, "entries");
          console.log("Looking for ID:", params.id);
          const foundEntry = history.find(e => e.id === params.id);
          if (foundEntry) {
            console.log("Found entry:", foundEntry);
            setEntry(foundEntry);
          } else {
            console.log("Entry not found. Available IDs:", history.map(e => e.id));
            setError("Analysis not found");
          }
        } catch (e) {
          console.error("Failed to load history:", e);
          setError("Failed to load analysis");
        }
      } else {
        console.log("No history found in localStorage");
        setError("No analysis history found");
      }
      setLoading(false);
    };

    // Try loading immediately
    loadEntry();
  }, [params.id]);

  const formatDate = (timestamp: number) => {
    return new Date(timestamp).toLocaleString();
  };

  const getRiskLevelColor = (level: string) => {
    switch (level) {
      case "HIGH": return "text-destructive";
      case "MEDIUM": return "text-secondary";
      case "LOW": return "text-primary";
      default: return "text-muted-foreground";
    }
  };

  const getRiskLevelBg = (level: string) => {
    switch (level) {
      case "HIGH": return "bg-destructive/10 text-destructive";
      case "MEDIUM": return "bg-secondary/10 text-secondary";
      case "LOW": return "bg-primary/10 text-primary";
      default: return "bg-muted text-muted-foreground";
    }
  };

  const shareAnalysis = () => {
    if (!entry) return;
    
    const shareText = `Job Analysis Result: ${entry.result.isFake ? "Fake Job" : "Legitimate Job"} (${(entry.result.confidence * 100).toFixed(1)}% confidence, ${entry.result.risk_level} risk)`;
    
    if (navigator.share) {
      navigator.share({
        title: "VeritasHire Job Analysis",
        text: shareText,
        url: window.location.href
      });
    } else {
      navigator.clipboard.writeText(shareText + " - " + window.location.href);
      alert("Analysis link copied to clipboard!");
    }
  };

  const downloadReport = () => {
    if (!entry) return;
    
    const report = `
VeritasHire Job Analysis Report
=============================
Date: ${formatDate(entry.timestamp)}
Result: ${entry.result.isFake ? "FAKE JOB" : "LEGITIMATE JOB"}
Confidence: ${(entry.result.confidence * 100).toFixed(1)}%
Risk Level: ${entry.result.risk_level}

Job Description:
----------------
${entry.jobDescription}

Risk Factors:
-------------
${entry.result.riskFactors ? entry.result.riskFactors.join("\n") : "None detected"}

Skills Found:
-------------
${entry.result.skills ? entry.result.skills.join("\n") : "None detected"}

Confidence Breakdown:
---------------------
Real: ${(entry.result.confidence_real * 100).toFixed(1)}%
Fake: ${(entry.result.confidence_fake * 100).toFixed(1)}%

Generated by VeritasHire - AI Job Fraud Detection
    `;
    
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `job-analysis-${entry.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>
    );
  }

  if (error || !entry) {
    return (
      <>
        <GrainOverlay />
        <Section maxWidth="4xl" className="min-h-screen flex items-center justify-center pt-16">
          <Card className="p-8 text-center max-w-md">
            <div className="h-20 w-20 rounded-full bg-destructive/10 flex items-center justify-center mx-auto mb-4">
              <AlertTriangle size={40} className="text-destructive" />
            </div>
            <h2 className="text-2xl font-heading font-bold mb-2">Analysis Not Found</h2>
            <p className="text-muted-foreground mb-6">
              {error || "The requested analysis could not be found."}
            </p>
            <Link href="/recent">
              <Button size="lg">
                <ArrowLeft className="mr-2" size={20} />
                Back to Recent Analysis
              </Button>
            </Link>
          </Card>
        </Section>
      </>
    );
  }

  return (
    <>
      <GrainOverlay />
      
      {/* Navbar */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-background/80 backdrop-blur-md border-b border-border/50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex items-center justify-between h-16">
            <div className="flex items-center gap-2">
              <Link href="/" className="flex items-center gap-2">
                <img 
                  src="/logo.svg" 
                  alt="VeritasHire Logo" 
                  width={40} 
                  height={40} 
                />
                <span className="font-heading font-bold text-xl text-foreground">VeritasHire</span>
              </Link>
            </div>
            <div className="flex gap-3">
              <Button variant="outline" size="sm" onClick={shareAnalysis}>
                <Share2 size={14} className="mr-2" />
                Share
              </Button>
              <Button variant="outline" size="sm" onClick={downloadReport}>
                <Download size={14} className="mr-2" />
                Download
              </Button>
              <Link href="/recent">
                <Button variant="outline" size="sm">
                  <ArrowLeft size={14} className="mr-2" />
                  Back to Recent
                </Button>
              </Link>
            </div>
          </div>
        </div>
      </nav>
      
      {/* Hero Section */}
      <Section maxWidth="4xl" className="relative min-h-[40vh] flex items-center justify-center pt-16">
        <BlobBackground color="moss" shapeIndex={0} className="-top-20 -left-40" />
        <BlobBackground color="terracotta" shapeIndex={1} className="-bottom-20 -right-40" />
        
        <div className="text-center space-y-6 relative z-10">
          <div className="inline-flex items-center gap-2 px-6 py-3 rounded-full bg-primary/10 text-primary font-semibold text-sm">
            <FileText size={16} />
            Analysis Report
          </div>
          
          <h1 className="text-4xl md:text-6xl font-heading font-extrabold leading-tight">
            Job Analysis
            <span className="block text-primary">Report</span>
          </h1>
          
          <div className="flex items-center justify-center gap-4 text-sm text-muted-foreground">
            <div className="flex items-center gap-1">
              <Calendar size={14} />
              {formatDate(entry.timestamp)}
            </div>
            <div className="flex items-center gap-1">
              <BarChart3 size={14} />
              ID: {entry.id}
            </div>
          </div>
        </div>
      </Section>

      {/* Main Analysis Content */}
      <Section maxWidth="4xl">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, ease: "easeOut" }}
          className="space-y-8"
        >
          {/* Result Summary */}
          <Card
            asymmetric
            shapeIndex={2}
            className={`p-8 md:p-10 ${
              entry.result.isFake ? "border-destructive/30" : "border-primary/30"
            }`}
          >
            <div className="space-y-6">
              {/* Header */}
              <div className="flex flex-col md:flex-row items-start md:items-center gap-4">
                {entry.result.isFake ? (
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: "spring", delay: 0.2 }}
                    className="h-20 w-20 rounded-full bg-destructive/10 flex items-center justify-center"
                  >
                    <ShieldAlert size={40} className="text-destructive" />
                  </motion.div>
                ) : (
                  <motion.div
                    initial={{ scale: 0 }}
                    animate={{ scale: 1 }}
                    transition={{ type: "spring", delay: 0.2 }}
                    className="h-20 w-20 rounded-full bg-primary/10 flex items-center justify-center"
                  >
                    <Shield size={40} className="text-primary" />
                  </motion.div>
                )}
                <div className="flex-1">
                  <h2 className="text-3xl font-heading font-bold mb-1">
                    {entry.result.isFake ? "Potentially Fake" : "Likely Legitimate"}
                  </h2>
                  <div className="flex items-center gap-3">
                    <Badge
                      variant={entry.result.isFake ? "destructive" : "success"}
                      className="text-base"
                    >
                      Confidence: {(entry.result.confidence * 100).toFixed(1)}%
                    </Badge>
                    <Badge className={getRiskLevelBg(entry.result.risk_level)}>
                      <AlertTriangle size={12} className="mr-1" />
                      {entry.result.risk_level} Risk
                    </Badge>
                  </div>
                </div>
              </div>

              {/* Confidence Bars */}
              <div className="grid md:grid-cols-2 gap-6">
                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <span className="font-semibold flex items-center gap-2">
                      <Shield size={16} className="text-primary" />
                      Legitimate
                    </span>
                    <span className="text-2xl font-heading font-bold text-primary">
                      {(entry.result.confidence_real * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="h-4 rounded-full bg-muted overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${entry.result.confidence_real * 100}%` }}
                      transition={{ duration: 1, delay: 0.3, ease: "easeOut" }}
                      className="h-full rounded-full bg-gradient-to-r from-primary to-primary/80"
                    />
                  </div>
                </div>

                <div className="space-y-2">
                  <div className="flex justify-between items-center">
                    <span className="font-semibold flex items-center gap-2">
                      <ShieldAlert size={16} className="text-destructive" />
                      Fake
                    </span>
                    <span className="text-2xl font-heading font-bold text-destructive">
                      {(entry.result.confidence_fake * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="h-4 rounded-full bg-muted overflow-hidden">
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${entry.result.confidence_fake * 100}%` }}
                      transition={{ duration: 1, delay: 0.4, ease: "easeOut" }}
                      className="h-full rounded-full bg-gradient-to-r from-destructive to-destructive/80"
                    />
                  </div>
                </div>
              </div>

              {/* Risk Factors */}
              {entry.result.riskFactors && entry.result.riskFactors.length > 0 && (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.6 }}
                  className="space-y-3 p-6 rounded-2xl bg-destructive/5 border border-destructive/20"
                >
                  <h3 className="font-heading font-semibold text-lg flex items-center gap-2">
                    <AlertTriangle size={20} className="text-destructive" />
                    Red Flags Detected ({entry.result.riskFactors.length})
                  </h3>
                  <div className="flex flex-wrap gap-2">
                    {entry.result.riskFactors.map((factor, index) => (
                      <motion.div
                        key={index}
                        initial={{ opacity: 0, scale: 0.8 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ delay: 0.7 + index * 0.05 }}
                      >
                        <Badge variant="destructive">{factor}</Badge>
                      </motion.div>
                    ))}
                  </div>
                </motion.div>
              )}

              {/* No Risk Factors */}
              {!entry.result.riskFactors || entry.result.riskFactors.length === 0 ? (
                <motion.div
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.6 }}
                >
                  <Badge variant="success" className="text-base px-6 py-3">
                    <CheckCircle size={16} className="mr-2" />
                    No significant red flags detected
                  </Badge>
                </motion.div>
              ) : null}
            </div>
          </Card>

          {/* Job Description */}
          <Card asymmetric shapeIndex={1} className="p-8">
            <div className="space-y-4">
              <h3 className="text-2xl font-heading font-bold flex items-center gap-2">
                <FileText size={24} className="text-primary" />
                Job Description
              </h3>
              <div className="bg-muted/30 rounded-2xl p-6">
                <pre className="whitespace-pre-wrap text-sm leading-relaxed text-foreground">
                  {entry.jobDescription}
                </pre>
              </div>
            </div>
          </Card>

          {/* Skill Suggestions */}
          {!entry.result.isFake && entry.result.skills && entry.result.skills.length > 0 && (
            <SkillSuggestions skills={entry.result.skills} />
          )}
        </motion.div>
      </Section>
    </>
  );
}
